language: java
install:
- TERM=dumb ./gradlew -q assemble
script:
- TERM=dumb ./gradlew build jacocoTestReport jacocoRootReport
jdk:
- oraclejdk8
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- chmod +x gradlew
after_success:
- ./gradlew coveralls
- ./gradlew bintrayUpload -PbintrayUsername=$bintrayUsername -PbintrayApiKey=$bintrayApiKey
env:
  global:
  - secure: CAp7iVZj6nHXdVsge7jFC8iHD+MBAcJnX2sADgOKub6iSstVAlmNGan+5l3ZqjVU/e4PQdC5nChov8EudQDZXVLQI5bLSrWukJsTiVgRDmWO7fJUWH5gU9NjXz97gC7My2n4+rFsdCkRIXilBqRQjlLNq56wzTT9c03rU1b211p1Xf143t6PHvPrIFS9OfKtv7AjP/YO0E6P5srqu8yKEPF4D814ktkcJmoEuuQrwjHUX3e0FbzO3DoC7zMKWk9MgLkP4rTU7aXsWfi3tthIOWs/tRQaviGkaOvZPCuko3t8Mg792lSmmB0civh3u0eix6YZ9SVPFK+ftpQiOLwx2LL9jiTme+X+/2ztrSw+lQkhgDEF7+ZYfccx40/1jx+El6mlMWAZO9KoAXwGzXKha7A/ar5yaMLMdr3Na3Kt3UNZr16bD8ohuRvsZInUhggklhzSsv9g0xEd6c4GspOBZ+tAHlo/PWvfVobII+kDsJMoySjvkz1h1PsQVOl0gS8szfRqeZNNR5ZFA7QtZJP0BFaYK3OV/orAcRDzsA0Wp+/0zz/Kdb312yjqCYEK4SGGgVHKz61dIeiZ4PeM5XREtKGf+WK55Qa2PAPEhfsJI3g+gtjvtMaYtIpe27wErCjQGABI+Il4x/2bGe7y5t0gqIVbzMo1ejLOR1p2xZA4Odk=
  - secure: EI59TsEPTc8KWeUl33lTdp47S2iGqd+zxwzunvl2L8CYUcx3ZTn0wCQ3dP7aBhkNU1Scxr1ZdCXsqP0oYAI8CgQo0ffGXi6MVsHPfu3n5tdIv4W94Lnaz1M3p6KNfnpnY4/h4Gjr7z8vS5Au6TROVbPY3psXtfQN9gfLBapLMkmEApVBaXyjX3EHfFzC1EdO+OTEX6uqkzKvB3nLcGPt0VqGpIOkQD3M1X6dyWAQeC5qsomX4wE7UwX2rEf13adLQ2GfPjS1w0vyjC3+OSp7LocJxmJRzFLWc7nxT9nl4Mdz7OKbaT6lqmhQ81UToSO93F25UBrFbbe9JPyy1UocMADWPr0mdrStu2tWG6TdCXtr3he4ABtLnJmLQSzZ99HOfDXrGdaapvzETyZkF1+qPb/Kxp8t5/YgWj1dnZ2qqWo3d8GW4PaU93CgT4TkctjUh5wj812b5CTYQnbmJDIstywnm5BDcyV6n5FqTUsFZpm4dR7yC6gqFZPam8dtvLHNawIuqeEHiztd8Tdwtvifyzg7EPRbkApAFJ5vAjpxr0qyRG573jki0VORGbFxgn1lHOOPm7UIFk46+44/FrIKw+sYY0xGhVFHoUVO5vhEHR80OABXFjw1tpnGsW73MwDHS5iyfOxV6lRLOsrOr3O3rJ+WTrHTaVejkp1XGWeRh0E=
